pages:
  - name: ホーム - 未来
    path: /2022-11-28
  - name: ホーム - 現在
    path: /
  - name: ホーム - 過去
    path: /2022-10-26
  - name: 出走表
    path: /races/d6d39349-2c61-48bb-a91c-4a16ee6742a1/race-card
  - name: オッズ - 締め切り前
    path: /races/d6d39349-2c61-48bb-a91c-4a16ee6742a1/odds
  - name: オッズ - 締め切り後
    path: /races/6de0c655-4483-42f1-80b2-7b6c9d2bf2aa/odds
  - name: 結果
    path: /races/f45152a0-b6eb-417f-bdc9-d36b249b498b/result
viewports:
  - name: Pixel 5
    width: 393
    height: 851
  - name: Kindle Fire HDX
    width: 800
    height: 1280
  - name: Desktop
    width: 1280
    height: 720